// FETCH OCCUPANT
export const FETCH_OCCUPANTS_LIST = 'FETCH_OCCUPANT_LIST';
export const FETCH_OCCUPANTS_LIST_SUCCESS = 'FETCH_OCCUPANT_LIST_SUCCESS';
export const FETCH_OCCUPANTS_LIST_ERROR = 'FETCH_OCCUPANT_LIST_ERROR';
// FETCH SINGLE OCCUPANT
export const FETCH_SINGLE_OCCUPANT = 'FETCH_SINGLE_OCCUPANT';
export const FETCH_SINGLE_OCCUPANT_SUCCESS = 'FETCH_SINGLE_OCCUPANT_SUCCESS';
export const FETCH_SINGLE_OCCUPANT_ERROR = 'FETCH_SINGLE_OCCUPANT_ERROR';
// ADD OCCUPANT
export const ADD_OCCUPANT = 'ADD_OCCUPANT';
export const ADD_OCCUPANT_SUCCESS = 'ADD_OCCUPANT_SUCCESS';
export const ADD_OCCUPANT_ERROR = 'ADD_OCCUPANT_ERROR';
// UPDATE OCCUPANT
export const UPDATE_OCCUPANT = 'UPDATE_OCCUPANT';
export const UPDATE_OCCUPANT_SUCCESS = 'UPDATE_OCCUPANT_SUCCESS';
export const UPDATE_OCCUPANT_ERROR = 'UPDATE_OCCUPANT_ERROR';
// ADD OCCUPANT
export const REMOVE_OCCUPANT = 'REMOVE_OCCUPANT';
export const REMOVE_OCCUPANT_SUCCESS = 'REMOVE_OCCUPANT_SUCCESS';
export const REMOVE_OCCUPANT_ERROR = 'REMOVE_OCCUPANT_ERROR';
