// FETCH REPORT
export const FETCH_REPORTS_LIST = 'FETCH_REPORT_LIST';
export const FETCH_REPORTS_LIST_SUCCESS = 'FETCH_REPORT_LIST_SUCCESS';
export const FETCH_REPORTS_LIST_ERROR = 'FETCH_REPORT_LIST_ERROR';
// FETCH SINGLE REPORT
export const FETCH_SINGLE_REPORT = 'FETCH_SINGLE_REPORT';
export const FETCH_SINGLE_REPORT_SUCCESS = 'FETCH_SINGLE_REPORT_SUCCESS';
export const FETCH_SINGLE_REPORT_ERROR = 'FETCH_SINGLE_REPORT_ERROR';
// FETCH GAME_RESULT_DETAILS
export const FETCH_GAME_RESULT_DETAILS = 'FETCH_GAME_RESULT_DETAILS';
export const FETCH_GAME_RESULT_DETAILS_SUCCESS =
  'FETCH_GAME_RESULT_DETAILS_SUCCESS';
export const FETCH_GAME_RESULT_DETAILS_ERROR =
  'FETCH_GAME_RESULT_DETAILS_ERROR';
// ADD REPORT
export const ADD_REPORT = 'ADD_REPORT';
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS';
export const ADD_REPORT_ERROR = 'ADD_REPORT_ERROR';
// UPDATE REPORT
export const UPDATE_REPORT = 'UPDATE_REPORT';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_ERROR = 'UPDATE_REPORT_ERROR';
// ADD REPORT
export const REMOVE_REPORT = 'REMOVE_REPORT';
export const REMOVE_REPORT_SUCCESS = 'REMOVE_REPORT_SUCCESS';
export const REMOVE_REPORT_ERROR = 'REMOVE_REPORT_ERROR';
