// FETCH OCCUPANT
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR';
// ADD OCCUPANT
export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';
export const ADD_USER_DETAILS_SUCCESS = 'ADD_USER_DETAILS_SUCCESS';
export const ADD_USER_DETAILS_ERROR = 'ADD_USER_DETAILS_ERROR';
// UPDATE OCCUPANT
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_ERROR = 'UPDATE_USER_DETAILS_ERROR';
// ADD USER_DETAILS
export const REMOVE_USER_DETAILS = 'REMOVE_USER_DETAILS';
export const REMOVE_USER_DETAILS_SUCCESS = 'REMOVE_USER_DETAILS_SUCCESS';
export const REMOVE_USER_DETAILS_ERROR = 'REMOVE_USER_DETAILS_ERROR';
