// FETCH GAME_SESSION
export const FETCH_GAME_SESSION = 'FETCH_GAME_SESSION';
export const FETCH_GAME_SESSION_SUCCESS = 'FETCH_GAME_SESSION_SUCCESS';
export const FETCH_GAME_SESSION_ERROR = 'FETCH_GAME_SESSION_ERROR';
// ADD GAME_SESSION
export const ADD_GAME_SESSION = 'ADD_GAME_SESSION';
export const ADD_GAME_SESSION_SUCCESS = 'ADD_GAME_SESSION_SUCCESS';
export const ADD_GAME_SESSION_ERROR = 'ADD_GAME_SESSION_ERROR';
// UPDATE GAME_SESSION
export const UPDATE_GAME_SESSION = 'UPDATE_GAME_SESSION';
export const UPDATE_GAME_SESSION_SUCCESS = 'UPDATE_GAME_SESSION_SUCCESS';
export const UPDATE_GAME_SESSION_ERROR = 'UPDATE_GAME_SESSION_ERROR';
// ADD GAME_SESSION
export const REMOVE_GAME_SESSION = 'REMOVE_GAME_SESSION';
export const REMOVE_GAME_SESSION_SUCCESS = 'REMOVE_GAME_SESSION_SUCCESS';
export const REMOVE_GAME_SESSION_ERROR = 'REMOVE_GAME_SESSION_ERROR';
// SUBMIT_GAME_STAGE_RESULT
export const SUBMIT_GAME_STAGE_RESULT = 'SUBMIT_GAME_STAGE_RESULT';
export const SUBMIT_GAME_STAGE_RESULT_SUCCESS =
  'SUBMIT_GAME_STAGE_RESULT_SUCCESS';
export const SUBMIT_GAME_STAGE_RESULT_ERROR = 'SUBMIT_GAME_STAGE_RESULT_ERROR';

//#### LETTERING STAGE THREE STORAGE ####
// ADD_LETTERING_STAGE_THREE_EXERCISE_ONE
export const ADD_LETTERING_STAGE_THREE_EXERCISE_ONE =
  'ADD_LETTERING_STAGE_THREE_EXERCISE_ONE';
export const ADD_LETTERING_STAGE_THREE_EXERCISE_ONE_SUCCESS =
  'ADD_LETTERING_STAGE_THREE_EXERCISE_ONE_SUCCESS';
export const ADD_LETTERING_STAGE_THREE_EXERCISE_ONE_ERROR =
  'ADD_LETTERING_STAGE_THREE_EXERCISE_ONE_ERROR';
// FETCH_LETTERING_STAGE_THREE_EXERCISE_ONE
export const FETCH_LETTERING_STAGE_THREE_EXERCISE_ONE =
  'FETCH_LETTERING_STAGE_THREE_EXERCISE_ONE';
export const FETCH_LETTERING_STAGE_THREE_EXERCISE_ONE_SUCCESS =
  'FETCH_LETTERING_STAGE_THREE_EXERCISE_ONE_SUCCESS';
export const FETCH_LETTERING_STAGE_THREE_EXERCISE_ONE_ERROR =
  'FETCH_LETTERING_STAGE_THREE_EXERCISE_ONE_ERROR';
