// FETCH SPEECH_TO_TEXT
export const FETCH_SPEECH_TO_TEXT = 'FETCH_SPEECH_TO_TEXT';
export const FETCH_SPEECH_TO_TEXT_SUCCESS = 'FETCH_SPEECH_TO_TEXT_SUCCESS';
export const FETCH_SPEECH_TO_TEXT_ERROR = 'FETCH_SPEECH_TO_TEXT_ERROR';
// ADD SPEECH_TO_TEXT
export const ADD_SPEECH_TO_TEXT = 'ADD_SPEECH_TO_TEXT';
export const ADD_SPEECH_TO_TEXT_SUCCESS = 'ADD_SPEECH_TO_TEXT_SUCCESS';
export const ADD_SPEECH_TO_TEXT_ERROR = 'ADD_SPEECH_TO_TEXT_ERROR';