// FETCH REGISTER_USER
export const FETCH_REGISTER_USER = 'FETCH_REGISTER_USER';
export const FETCH_REGISTER_USER_SUCCESS = 'FETCH_REGISTER_USER_SUCCESS';
export const FETCH_REGISTER_USER_FAILURE = 'FETCH_REGISTER_USER_FAILURE';
// ADD REGISTER_USER
export const ADD_REGISTER_USER = 'ADD_REGISTER_USER';
export const ADD_REGISTER_USER_SUCCESS = 'ADD_REGISTER_USER_SUCCESS';
export const ADD_REGISTER_USER_FAILURE = 'ADD_REGISTER_USER_FAILURE';
