// FETCH REPORT
// export const FETCH_FORGOT_PASSWORD = 'FETCH_FORGOT_PASSWORD';
// export const FETCH_FORGOT_PASSWORD_SUCCESS = 'FETCH_FORGOT_PASSWORD_SUCCESS';
// export const FETCH_FORGOT_PASSWORD_ERROR = 'FETCH_FORGOT_PASSWORD_ERROR';

// SEND EMAIL
export const SEND_REGISTERED_EMAIL = 'SEND_REGISTERED_EMAIL';
export const SEND_REGISTERED_EMAIL_SUCCESS = 'SEND_REGISTERED_EMAIL_SUCCESS';
export const SEND_REGISTERED_EMAIL_ERROR = 'SEND_REGISTERED_EMAIL_ERROR';


// UPDATE PASSWORD
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_ERROR = 'UPDATE_USER_PASSWORD_ERROR';
