// FETCH LOGINUSER
export const FETCH_LOGINUSER = 'FETCH_LOGINUSER';
export const FETCH_LOGINUSER_SUCCESS = 'FETCH_LOGINUSER_SUCCESS';
export const FETCH_LOGINUSER_FAILURE = 'FETCH_LOGINUSER_FAILURE';
// ADD LOGINUSER
export const ADD_LOGINUSER = 'ADD_LOGINUSER';
export const ADD_LOGINUSER_SUCCESS = 'ADD_LOGINUSER_SUCCESS';
export const ADD_LOGINUSER_FAILURE = 'ADD_LOGINUSER_FAILURE';
